import = [
    "~/.config/alacritty/rose-pine.toml"
]

live_config_reload = true

[env]
TERM_PROGRAM = "Alacritty"

[font]
size = 12.0
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }

[window]
decorations = "none"
opacity = 1.0
