import = [
  "~/.config/alacritty/nightfox.toml"
]

live_config_reload = true

[env]
TERM_PROGRAM = "Alacritty"

[font]
size = 12.5
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[window]
decorations = "none"
opacity = 1.0
