#!/bin/bash

DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$DIR/plugins"
ITEM_DIR="$DIR/items"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="JetBrainsMono Nerd Font"

PADDING=3

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=34
  color=$BACKGROUND
  shadow=off
  position=top
  y_offset=6
  margin=12
  corner_radius=8
  sticky=on
)

DEF_PROPS=(
  icon.font="$ICON_FONT:Bold:18.0"
  icon.color=$MAGENTA
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Regular:13.0"
  label.color=$MAGENTA
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  background.color=0x00000000
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=0xffffffff
  popup.background.color=0x00000000
  popup.background.shadow.drawing=on
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

source $ITEM_DIR/apple.sh
source $ITEM_DIR/seperator.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/focus.sh

source $ITEM_DIR/time.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh

sketchybar --update
