#!/bin/bash

DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$DIR/plugins"
ITEM_DIR="$DIR/items"

FONT="Mononoki Nerd Font"
ICON_FONT="Mononoki Nerd Font"

PADDING=3

source "$DIR/icons.sh"

BAR_PROPS=(
  height=30
  color=0xcc000000
  shadow=on
  position=top
  y_offset=4
  margin=12
  corner_radius=8
  sticky=on
)

DEF_PROPS=(
  icon.font="$ICON_FONT:Regular:18.0"
  icon.color=0xffffffff
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Semibold:13.0"
  label.color=0xffffffff
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  backgorund.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=0xffffffff
  popup.background.color=0xcc000000
  popup.background.shadow.drawing=on
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

source $ITEM_DIR/apple.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/time.sh
source $ITEM_DIR/volume.sh

SPACE_ICONS=("1" "2" "3" "4") 

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                                 \
             --set space.$sid space=$sid                                 \
                              icon=${SPACE_ICONS[i]}                     \
                              background.color=0x44ffffff                \
                              background.corner_radius=5                 \
                              background.height=20                       \
                              background.drawing=off                     \
                              label.drawing=off                          \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"
done

sketchybar --add item space_separator left                         \
           --set space_separator icon=                            \
                                 padding_left=10                   \
                                 padding_right=10                  \
                                 label.drawing=off                 \
                                                                   \
           --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched

sketchybar --update
