#!/bin/bash

DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$DIR/plugins"
ITEM_DIR="$DIR/items"

FONT="Mononoki Nerd Font"
ICON_FONT="Mononoki Nerd Font"

PADDING=4

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=30
  color=$BG_COLOR
  shadow=on
  position=top
  y_offset=4
  margin=12
  corner_radius=8
  sticky=on
)

DEF_PROPS=(
  icon.font="$ICON_FONT:Regular:18.0"
  icon.color=$TEXT_COLOR
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Bold:13.0"
  label.color=$TEXT_COLOR
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  background.color=$BG_COLOR
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=0xffffffff
  popup.background.color=0x00000000
  popup.background.shadow.drawing=on
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/focus.sh

source $ITEM_DIR/time.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh

sketchybar --update
